version: '0.2'
language: en
dictionaryDefinitions:
  - name: custom-dict
    path: cspell/custom-dict.txt
dictionaries:
  - en_us
  - en-gb
  - softwareTerms
  - companies
  - custom-dict
  - ar
  - bn
  - el
  - he
  - lv
  - sv
import:
  - '@cspell/dict-python/cspell-ext.json'
  - '@cspell/dict-ar/cspell-ext.json'
  - '@cspell/dict-bn/cspell-ext.json'
  - '@cspell/dict-el/cspell-ext.json'
  - '@cspell/dict-he/cspell-ext.json'
  - '@cspell/dict-lv/cspell-ext.json'
  - '@cspell/dict-sv/cspell-ext.json'
useGitignore: true
ignorePaths:
  - node_modules
  - dist
  - build
